//go:build ignore

// gen_services.go generates service_versions_gen.go from the Tencent SDK
// modules in $GOMODCACHE. Each `tencentcloud-sdk-go/tencentcloud/<svc>/v<YYYYMMDD>`
// directory becomes one entry in `serviceVersions`; when a service has
// multiple versions vendored we pick the latest (lexicographic on YYYYMMDD).
//
// Run: `go generate ./internal/tencent/...`
//
// The file is `//go:build ignore` so the package compiles without it; only
// `go generate` (or `go run`) executes it.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

// Services we want in the map that don't live in tencentcloud-sdk-go (or for
// which the version string is intentionally empty). Keep this list small —
// adding to it is the only manual step required when the SDK gains a quirk.
var manualOverrides = map[string]string{
	"cos": "", // COS uses the object-storage REST API; SendRaw can't dispatch it.
}

const outputFile = "service_versions_gen.go"

var versionRE = regexp.MustCompile(`/tencentcloud/([^/@]+)(?:@[^/]+)?/v(\d{8})$`)

func main() {
	cache, err := goModCache()
	if err != nil {
		die("locate GOMODCACHE: %v", err)
	}
	root := filepath.Join(cache, "github.com", "tencentcloud", "tencentcloud-sdk-go", "tencentcloud")
	if _, err := os.Stat(root); err != nil {
		die("tencent SDK not in module cache at %s — run `go mod download` first", root)
	}

	versions := map[string]string{}
	err = filepath.WalkDir(root, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if !d.IsDir() {
			return nil
		}
		m := versionRE.FindStringSubmatch(path)
		if m == nil {
			return nil
		}
		svc, ver := m[1], m[2]
		// Lexicographic comparison works since the format is fixed YYYYMMDD.
		if existing, ok := versions[svc]; !ok || ver > existing {
			versions[svc] = ver
		}
		return nil
	})
	if err != nil {
		die("walk SDK: %v", err)
	}

	for svc, ver := range manualOverrides {
		// Overrides win even if the SDK happens to vendor the service —
		// the empty-string COS sentinel is load-bearing for SendRaw's
		// "use service-specific path" error.
		versions[svc] = ver
	}

	keys := make([]string, 0, len(versions))
	for k := range versions {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var buf bytes.Buffer
	buf.WriteString("// Code generated by gen_services.go; DO NOT EDIT.\n")
	buf.WriteString("// Run `go generate ./internal/tencent/...` to refresh after upgrading\n")
	buf.WriteString("// github.com/tencentcloud/tencentcloud-sdk-go.\n\n")
	buf.WriteString("package tencent\n\n")
	buf.WriteString("// serviceVersions maps Tencent service short names to the API version\n")
	buf.WriteString("// SendRaw passes to tchttp.CommonRequest. Source: the vendored Tencent\n")
	buf.WriteString("// SDK, picking the highest version per service. Empty string means the\n")
	buf.WriteString("// service does not use the generic action API (see SendRaw for the\n")
	buf.WriteString("// branch that handles this).\n")
	buf.WriteString("var serviceVersions = map[string]string{\n")
	for _, svc := range keys {
		ver := versions[svc]
		if ver == "" {
			buf.WriteString(fmt.Sprintf("\t%q: %q,\n", svc, ""))
			continue
		}
		// Reformat 20200324 → 2020-03-24 for readability.
		fmtted := ver[:4] + "-" + ver[4:6] + "-" + ver[6:]
		buf.WriteString(fmt.Sprintf("\t%q: %q,\n", svc, fmtted))
	}
	buf.WriteString("}\n")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		die("gofmt: %v\n--- source ---\n%s", err, buf.String())
	}
	if err := os.WriteFile(outputFile, formatted, 0o644); err != nil {
		die("write %s: %v", outputFile, err)
	}
	fmt.Printf("wrote %s with %d services\n", outputFile, len(versions))
	for _, svc := range keys {
		fmt.Printf("  %-12s %s\n", svc, versions[svc])
	}
}

func goModCache() (string, error) {
	out, err := exec.Command("go", "env", "GOMODCACHE").Output()
	if err != nil {
		return "", err
	}
	return strings.TrimSpace(string(out)), nil
}

func die(format string, a ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", a...)
	os.Exit(1)
}
