// Code generated by gen_services.go; DO NOT EDIT.
// Run `go generate ./internal/tencent/...` to refresh after upgrading
// github.com/tencentcloud/tencentcloud-sdk-go.

package tencent

// serviceVersions maps Tencent service short names to the API version
// SendRaw passes to tchttp.CommonRequest. Source: the vendored Tencent
// SDK, picking the highest version per service. Empty string means the
// service does not use the generic action API (see SendRaw for the
// branch that handles this).
var serviceVersions = map[string]string{
	"antiddos":   "2025-09-03",
	"billing":    "2018-07-09",
	"cam":        "2019-01-16",
	"cbs":        "2017-03-12",
	"cdb":        "2017-03-20",
	"cdn":        "2018-06-06",
	"clb":        "2018-03-17",
	"cloudaudit": "2019-03-19",
	"cls":        "2020-10-16",
	"cos":        "",
	"cvm":        "2017-03-12",
	"cynosdb":    "2019-01-07",
	"dc":         "2018-04-10",
	"lighthouse": "2020-03-24",
	"mongodb":    "2019-07-25",
	"monitor":    "2023-06-16",
	"postgres":   "2017-03-12",
	"redis":      "2018-04-12",
	"ssl":        "2019-12-05",
	"teo":        "2022-09-01",
	"tke":        "2022-05-01",
	"vpc":        "2017-03-12",
	"waf":        "2018-01-25",
}
