package api

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"regexp"
	"strconv"
	"strings"
	"time"

	"github.com/bgdnvk/clanker/internal/tencent"
)

// regionRegex matches every Tencent public region prefix that currently
// exists: ap-* (Asia-Pacific), na-* (North America), eu-* (Europe), sa-*
// (South America), and cn-* (mainland China). The optional numeric/letter
// suffix accommodates regions like `ap-shanghai-fsi`. Region NAMES never
// contain digits (those are zone-level only), so we don't accept them.
//
// Reviewer flagged that the unvalidated ?region= value was reaching the
// SDK signing layer verbatim — enabling enumeration of arbitrary
// Tencent endpoints and potentially driving unintended API charges.
var regionRegex = regexp.MustCompile(`^(ap|na|eu|sa|cn)-[a-z]+(-[a-z]+)?$`)

// errInvalidRegion is returned by validateRegion so the handler chokepoint
// can surface it as a 400 instead of the catch-all 401.
type errInvalidRegion struct{ value string }

func (e *errInvalidRegion) Error() string {
	return fmt.Sprintf("invalid region %q: must match prefix-name (e.g. ap-singapore, na-ashburn, eu-frankfurt)", e.value)
}

// validateRegion accepts an empty string (the daemon falls back to its
// configured default) or one of the patterns described above. Anything
// else is rejected before the value can reach the Tencent SDK.
func validateRegion(s string) error {
	if s == "" {
		return nil
	}
	if !regionRegex.MatchString(s) {
		return &errInvalidRegion{value: s}
	}
	return nil
}

func (s *Server) registerRoutes() {
	s.mux.HandleFunc("GET /api/v1/health", s.handleHealth)
	s.mux.HandleFunc("GET /api/v1/version", s.handleVersion)

	// Tencent read endpoints
	s.mux.HandleFunc("GET /api/v1/tencent/regions", s.handleTencentRegions)
	s.mux.HandleFunc("GET /api/v1/tencent/resources/{type}", s.handleTencentResources)
	s.mux.HandleFunc("GET /api/v1/tencent/sg-rules/{id}", s.handleTencentSGRules)
	s.mux.HandleFunc("GET /api/v1/tencent/kubeconfig/{cluster_id}", s.handleTencentKubeconfig)

	// Topology (Phase 7)
	s.mux.HandleFunc("GET /api/v1/tencent/topology", s.handleTencentTopology)
	s.mux.HandleFunc("GET /api/v1/tencent/scan/public-exposure", s.handleTencentPublicExposure)
	s.mux.HandleFunc("GET /api/v1/tencent/scan/clb-exposure", s.handleTencentCLBExposure)
	s.mux.HandleFunc("GET /api/v1/tencent/scan/idle-eips", s.handleTencentIdleEIPs)
	s.mux.HandleFunc("GET /api/v1/tencent/scan/unencrypted-cbs", s.handleTencentUnencryptedCBS)
	s.mux.HandleFunc("GET /api/v1/tencent/scan/cert-expiry", s.handleTencentCertExpiry)
	s.mux.HandleFunc("GET /api/v1/tencent/scan/cam-hygiene", s.handleTencentCAMHygiene)
	s.mux.HandleFunc("GET /api/v1/tencent/scan/db-exposure", s.handleTencentDBExposure)
	s.mux.HandleFunc("GET /api/v1/tencent/scan/waf-coverage", s.handleTencentWAFCoverage)
	s.mux.HandleFunc("GET /api/v1/tencent/scan/antiddos-coverage", s.handleTencentAntiDDoSCoverage)
	s.mux.HandleFunc("GET /api/v1/tencent/scan/audit-coverage", s.handleTencentAuditCoverage)
	s.mux.HandleFunc("GET /api/v1/tencent/metrics/cvm", s.handleTencentCVMMetrics)
	s.mux.HandleFunc("GET /api/v1/tencent/metrics/lighthouse", s.handleTencentLighthouseMetrics)
	s.mux.HandleFunc("GET /api/v1/tencent/cost/by-product", s.handleTencentCostByProduct)
	s.mux.HandleFunc("GET /api/v1/tencent/cost/resources", s.handleTencentCostResources)
	s.mux.HandleFunc("GET /api/v1/tencent/cost/vouchers", s.handleTencentCostVouchers)
	s.mux.HandleFunc("GET /api/v1/tencent/cost/voucher-usage/{voucher_id}", s.handleTencentCostVoucherUsage)
	s.mux.HandleFunc("GET /api/v1/tencent/cost/voucher-by-owner", s.handleTencentCostVoucherByOwner)

		// Maker (Phase 6) — apply a plan generated by `clanker ask --maker`.
	s.mux.HandleFunc("POST /api/v1/maker/apply", s.handleMakerApply)
	s.mux.HandleFunc("GET /api/v1/maker/history", s.handleMakerHistory)
	s.mux.HandleFunc("POST /api/v1/maker/plan", s.handleMakerPlan)
}

func (s *Server) handleHealth(w http.ResponseWriter, r *http.Request) {
	writeData(w, map[string]interface{}{
		"ok":     true,
		"uptime": time.Since(s.started).Round(time.Second).String(),
	})
}

// Version is wired by cmd/server.go via SetVersion so we don't import cmd here
// and create a cycle.
var serverVersion = "dev"

// SetVersion sets the version string returned by the /api/v1/version endpoint.
// Called once from cmd/server.go after main() initialises cmd.Version.
func SetVersion(v string) { serverVersion = v }

func (s *Server) handleVersion(w http.ResponseWriter, r *http.Request) {
	writeData(w, map[string]string{"version": serverVersion})
}

func (s *Server) handleTencentRegions(w http.ResponseWriter, r *http.Request) {
	client, err := s.tencentClient(r)
	if err != nil {
		writeTencentClientErr(w, err)
		return
	}
	regions, err := client.ListAllRegions()
	if err != nil {
		writeError(w, http.StatusBadGateway, "tencent_api_error", err.Error())
		return
	}
	writeData(w, regions)
}

func (s *Server) handleTencentResources(w http.ResponseWriter, r *http.Request) {
	resourceType := strings.ToLower(strings.TrimSpace(r.PathValue("type")))
	if resourceType == "" {
		writeError(w, http.StatusBadRequest, "missing_param", "resource type is required")
		return
	}

	client, err := s.tencentClient(r)
	if err != nil {
		writeTencentClientErr(w, err)
		return
	}

	// We reuse context.go's JSON gather funcs since they already emit the
	// shape we want to return. Each function targets the client's current
	// region; multi-region fan-out for HTTP is a future enhancement.
	ctx, cancel := context.WithTimeout(r.Context(), 60*time.Second)
	defer cancel()

	question := strings.ToLower(resourceType) // makes context.go pick the right section
	raw, err := client.GetRelevantContext(ctx, question)
	if err != nil {
		writeError(w, http.StatusBadGateway, "tencent_api_error", err.Error())
		return
	}
	// GetRelevantContext returns multi-section text; for an HTTP endpoint
	// we want a single-typed JSON answer. Strip the wrapper text and parse
	// just the requested section. Simpler approach: call the typed gather
	// directly.
	body, err := gatherTencentByType(ctx, client, resourceType)
	if err != nil {
		// Service not enabled or unsupported — return an empty list with
		// the underlying reason so the dashboard can show "no items + reason".
		writeJSON(w, http.StatusOK, map[string]interface{}{
			"data":    []interface{}{},
			"warning": err.Error(),
		})
		_ = raw
		return
	}
	if strings.TrimSpace(body) == "" {
		writeData(w, []interface{}{})
		return
	}
	writeRawData(w, body)
}

// gatherTencentByType returns a typed JSON section (already JSON-encoded) for
// the given resource type. Returns "" with no error when the type matches but
// no resources exist; an error when the type is unsupported or the SDK call
// fails.
func gatherTencentByType(ctx context.Context, client *tencent.Client, resourceType string) (string, error) {
	switch resourceType {
	case "cvm", "instance", "instances":
		return client.JSONCVMs(ctx)
	case "vpc", "vpcs":
		return client.JSONVPCs(ctx)
	case "sg", "sgs", "security-group", "security-groups":
		return client.JSONSecurityGroups(ctx)
	case "mysql", "cdb":
		return client.JSONMySQL(ctx)
	case "postgres", "postgresql", "pg":
		return client.JSONPostgres(ctx)
	case "cos", "buckets", "bucket":
		return client.JSONCOS(ctx)
	case "tke", "k8s", "clusters", "kubernetes":
		return client.JSONTKE(ctx)
	case "clb", "lb", "lbs", "load-balancer", "load-balancers":
		return client.JSONCLB(ctx)
	case "eip", "eips", "address", "addresses":
		return client.JSONEIP(ctx)
	case "cbs", "disk", "disks", "volume", "volumes":
		return client.JSONCBS(ctx)
	case "ssl", "cert", "certs", "certificate", "certificates":
		return client.JSONSSL(ctx)
	case "cam", "iam", "user", "users":
		return client.JSONCAM(ctx)
	case "redis", "valkey":
		return client.JSONRedis(ctx)
	case "mongo", "mongodb":
		return client.JSONMongoDB(ctx)
	case "cynosdb", "tdsql-c", "tdsqlc":
		return client.JSONCynosDB(ctx)
	case "cdn", "cdn-domains":
		return client.JSONCDN(ctx)
	case "edgeone", "teo", "zones":
		return client.JSONEdgeOne(ctx)
	case "waf", "waf-hosts":
		return client.JSONWAF(ctx)
	case "antiddos", "ddos":
		return client.JSONAntiDDoS(ctx)
	case "nat", "nat-gateway", "natgateway":
		return client.JSONNATGateways(ctx)
	case "vpn", "vpn-gateway", "vpngateway":
		return client.JSONVPNGateways(ctx)
	case "ccn", "cloud-connect":
		return client.JSONCCNs(ctx)
	case "dc", "direct-connect", "directconnect":
		return client.JSONDirectConnects(ctx)
	case "monitor", "alarm", "alarms", "alarm-policy":
		return client.JSONAlarmPolicies(ctx)
	case "cls", "log", "logs", "log-topics":
		return client.JSONCLSTopics(ctx)
	case "cloudaudit", "audit", "tracks":
		return client.JSONCloudAudit(ctx)
	case "lighthouse", "lh":
		return client.JSONLighthouses(ctx)
	default:
		return "", fmt.Errorf("unsupported resource type %q", resourceType)
	}
}

func (s *Server) handleTencentSGRules(w http.ResponseWriter, r *http.Request) {
	sgID := strings.TrimSpace(r.PathValue("id"))
	if sgID == "" {
		writeError(w, http.StatusBadRequest, "missing_param", "sg id is required")
		return
	}
	client, err := s.tencentClient(r)
	if err != nil {
		writeTencentClientErr(w, err)
		return
	}
	body, err := client.JSONSGRules(r.Context(), sgID)
	if err != nil {
		writeError(w, http.StatusBadGateway, "tencent_api_error", err.Error())
		return
	}
	writeRawData(w, body)
}

func (s *Server) handleTencentKubeconfig(w http.ResponseWriter, r *http.Request) {
	clusterID := strings.TrimSpace(r.PathValue("cluster_id"))
	if clusterID == "" {
		writeError(w, http.StatusBadRequest, "missing_param", "cluster_id is required")
		return
	}
	publicEndpoint := strings.EqualFold(r.URL.Query().Get("public"), "true")
	client, err := s.tencentClient(r)
	if err != nil {
		writeTencentClientErr(w, err)
		return
	}
	kc, err := client.FetchKubeconfig(r.Context(), clusterID, publicEndpoint)
	if err != nil {
		writeError(w, http.StatusBadGateway, "tencent_api_error", err.Error())
		return
	}
	writeJSON(w, http.StatusOK, map[string]interface{}{
		"data": map[string]string{
			"cluster_id": clusterID,
			"kubeconfig": kc,
		},
	})
}

func (s *Server) handleTencentTopology(w http.ResponseWriter, r *http.Request) {
	client, err := s.tencentClient(r)
	if err != nil {
		writeTencentClientErr(w, err)
		return
	}
	region := strings.TrimSpace(r.URL.Query().Get("region"))
	body, err := client.TopologyJSON(r.Context(), region)
	if err != nil {
		writeError(w, http.StatusBadGateway, "tencent_api_error", err.Error())
		return
	}
	writeRawData(w, body)
}

func (s *Server) handleTencentPublicExposure(w http.ResponseWriter, r *http.Request) {
	client, err := s.tencentClient(r)
	if err != nil {
		writeTencentClientErr(w, err)
		return
	}
	region := strings.TrimSpace(r.URL.Query().Get("region"))
	body, err := client.PublicExposureScanJSON(r.Context(), region)
	if err != nil {
		writeError(w, http.StatusBadGateway, "tencent_api_error", err.Error())
		return
	}
	writeRawData(w, body)
}

// tencentClient builds a Tencent client for this request. The region can be
// overridden per request via ?region=ap-jakarta; otherwise the daemon's
// default (resolved from config / env at startup) is used. Returns an
// *errInvalidRegion when the query param fails validation so handlers can
// distinguish a client-mistake (400) from a credential failure (401).
func (s *Server) tencentClient(r *http.Request) (*tencent.Client, error) {
	creds := tencent.ResolveCredentials()
	if region := strings.TrimSpace(r.URL.Query().Get("region")); region != "" {
		if err := validateRegion(region); err != nil {
			return nil, err
		}
		creds.Region = region
	}
	return tencent.NewClient(creds, s.cfg.Debug)
}

// writeTencentClientErr emits the right status+code envelope for the two
// failure modes of tencentClient. Use this from every handler that calls
// tencentClient so the validation surface stays consistent.
func writeTencentClientErr(w http.ResponseWriter, err error) {
	var ir *errInvalidRegion
	if errors.As(err, &ir) {
		writeError(w, http.StatusBadRequest, "invalid_region", err.Error())
		return
	}
	writeTencentClientErr(w, err)
}

// jsonValid is used by tests to assert that an internal JSON payload is
// well-formed; kept here so handlers and tests share one definition.
func jsonValid(s string) bool {
	var v interface{}
	return json.Unmarshal([]byte(s), &v) == nil
}

func (s *Server) handleTencentCLBExposure(w http.ResponseWriter, r *http.Request) {
	client, err := s.tencentClient(r)
	if err != nil {
		writeTencentClientErr(w, err)
		return
	}
	region := strings.TrimSpace(r.URL.Query().Get("region"))
	body, err := client.CLBExposureScanJSON(r.Context(), region)
	if err != nil {
		writeError(w, http.StatusBadGateway, "tencent_api_error", err.Error())
		return
	}
	writeRawData(w, body)
}

func (s *Server) handleTencentIdleEIPs(w http.ResponseWriter, r *http.Request) {
	client, err := s.tencentClient(r)
	if err != nil {
		writeTencentClientErr(w, err)
		return
	}
	region := strings.TrimSpace(r.URL.Query().Get("region"))
	body, err := client.IdleEIPScanJSON(r.Context(), region)
	if err != nil {
		writeError(w, http.StatusBadGateway, "tencent_api_error", err.Error())
		return
	}
	writeRawData(w, body)
}

func (s *Server) handleTencentUnencryptedCBS(w http.ResponseWriter, r *http.Request) {
	client, err := s.tencentClient(r)
	if err != nil {
		writeTencentClientErr(w, err)
		return
	}
	region := strings.TrimSpace(r.URL.Query().Get("region"))
	body, err := client.UnencryptedCBSScanJSON(r.Context(), region)
	if err != nil {
		writeError(w, http.StatusBadGateway, "tencent_api_error", err.Error())
		return
	}
	writeRawData(w, body)
}

func (s *Server) handleTencentCertExpiry(w http.ResponseWriter, r *http.Request) {
	client, err := s.tencentClient(r)
	if err != nil {
		writeTencentClientErr(w, err)
		return
	}
	days := 30
	if v := strings.TrimSpace(r.URL.Query().Get("days")); v != "" {
		if n, err := strconv.Atoi(v); err == nil && n > 0 {
			days = n
		}
	}
	body, err := client.CertExpiryScanJSON(r.Context(), days)
	if err != nil {
		writeError(w, http.StatusBadGateway, "tencent_api_error", err.Error())
		return
	}
	writeRawData(w, body)
}

func (s *Server) handleTencentCAMHygiene(w http.ResponseWriter, r *http.Request) {
	client, err := s.tencentClient(r)
	if err != nil {
		writeTencentClientErr(w, err)
		return
	}
	body, err := client.CAMHygieneScanJSON(r.Context())
	if err != nil {
		writeError(w, http.StatusBadGateway, "tencent_api_error", err.Error())
		return
	}
	writeRawData(w, body)
}

func (s *Server) handleTencentDBExposure(w http.ResponseWriter, r *http.Request) {
	client, err := s.tencentClient(r)
	if err != nil {
		writeTencentClientErr(w, err)
		return
	}
	region := strings.TrimSpace(r.URL.Query().Get("region"))
	body, err := client.DBExposureScanJSON(r.Context(), region)
	if err != nil {
		writeError(w, http.StatusBadGateway, "tencent_api_error", err.Error())
		return
	}
	writeRawData(w, body)
}

func (s *Server) handleTencentWAFCoverage(w http.ResponseWriter, r *http.Request) {
	client, err := s.tencentClient(r)
	if err != nil {
		writeTencentClientErr(w, err)
		return
	}
	body, err := client.WAFCoverageScanJSON(r.Context())
	if err != nil {
		writeError(w, http.StatusBadGateway, "tencent_api_error", err.Error())
		return
	}
	writeRawData(w, body)
}

func (s *Server) handleTencentAntiDDoSCoverage(w http.ResponseWriter, r *http.Request) {
	client, err := s.tencentClient(r)
	if err != nil {
		writeTencentClientErr(w, err)
		return
	}
	region := strings.TrimSpace(r.URL.Query().Get("region"))
	body, err := client.AntiDDoSCoverageScanJSON(r.Context(), region)
	if err != nil {
		writeError(w, http.StatusBadGateway, "tencent_api_error", err.Error())
		return
	}
	writeRawData(w, body)
}

func (s *Server) handleTencentAuditCoverage(w http.ResponseWriter, r *http.Request) {
	client, err := s.tencentClient(r)
	if err != nil {
		writeTencentClientErr(w, err)
		return
	}
	body, err := client.AuditLogCoverageScanJSON(r.Context())
	if err != nil {
		writeError(w, http.StatusBadGateway, "tencent_api_error", err.Error())
		return
	}
	writeRawData(w, body)
}

func (s *Server) handleTencentCVMMetrics(w http.ResponseWriter, r *http.Request) {
	client, err := s.tencentClient(r)
	if err != nil {
		writeTencentClientErr(w, err)
		return
	}
	region := strings.TrimSpace(r.URL.Query().Get("region"))
	metric := strings.TrimSpace(r.URL.Query().Get("metric"))
	minutes := 60
	if v := strings.TrimSpace(r.URL.Query().Get("minutes")); v != "" {
		if n, err := strconv.Atoi(v); err == nil && n > 0 {
			minutes = n
		}
	}
	body, err := client.CVMMetricsJSON(r.Context(), region, metric, minutes)
	if err != nil {
		writeError(w, http.StatusBadGateway, "tencent_api_error", err.Error())
		return
	}
	writeRawData(w, body)
}

// handleTencentLighthouseMetrics mirrors handleTencentCVMMetrics but for the
// Lighthouse product line (namespace QCE/LIGHTHOUSE). Default metric is
// Cpu_Usage. Other valid names: Mem_Usage, Public_Bandwidth_In,
// Public_Bandwidth_Out, Internal_Bandwidth_In, Internal_Bandwidth_Out.
func (s *Server) handleTencentLighthouseMetrics(w http.ResponseWriter, r *http.Request) {
	client, err := s.tencentClient(r)
	if err != nil {
		writeTencentClientErr(w, err)
		return
	}
	region := strings.TrimSpace(r.URL.Query().Get("region"))
	metric := strings.TrimSpace(r.URL.Query().Get("metric"))
	minutes := 60
	if v := strings.TrimSpace(r.URL.Query().Get("minutes")); v != "" {
		if n, err := strconv.Atoi(v); err == nil && n > 0 {
			minutes = n
		}
	}
	body, err := client.LighthouseMetricsJSON(r.Context(), region, metric, minutes)
	if err != nil {
		writeError(w, http.StatusBadGateway, "tencent_api_error", err.Error())
		return
	}
	writeRawData(w, body)
}

func (s *Server) handleTencentCostByProduct(w http.ResponseWriter, r *http.Request) {
	client, err := s.tencentClient(r)
	if err != nil {
		writeTencentClientErr(w, err)
		return
	}
	month := strings.TrimSpace(r.URL.Query().Get("month"))
	body, err := client.BillByProductJSON(r.Context(), month)
	if err != nil {
		writeError(w, http.StatusBadGateway, "tencent_api_error", err.Error())
		return
	}
	writeRawData(w, body)
}

func (s *Server) handleTencentCostResources(w http.ResponseWriter, r *http.Request) {
	client, err := s.tencentClient(r)
	if err != nil {
		writeTencentClientErr(w, err)
		return
	}
	month := strings.TrimSpace(r.URL.Query().Get("month"))
	top := 50
	if v := strings.TrimSpace(r.URL.Query().Get("top")); v != "" {
		if n, err := strconv.Atoi(v); err == nil && n > 0 {
			top = n
		}
	}
	body, err := client.BillResourceTopJSON(r.Context(), month, top)
	if err != nil {
		writeError(w, http.StatusBadGateway, "tencent_api_error", err.Error())
		return
	}
	writeRawData(w, body)
}

// handleTencentCostVouchers returns the account's vouchers plus a per-owner-UIN
// spend breakdown. Optional ?status= filters by Tencent's voucher-status enum
// (unUsed/used/delivered/cancel/overdue).
func (s *Server) handleTencentCostVouchers(w http.ResponseWriter, r *http.Request) {
	client, err := s.tencentClient(r)
	if err != nil {
		writeTencentClientErr(w, err)
		return
	}
	status := strings.TrimSpace(r.URL.Query().Get("status"))
	body, err := client.VouchersJSON(r.Context(), status)
	if err != nil {
		writeError(w, http.StatusBadGateway, "tencent_api_error", err.Error())
		return
	}
	writeRawData(w, body)
}

// handleTencentCostVoucherByOwner returns a month's voucher deduction grouped
// by the owner account UIN of each billed resource (?month=YYYY-MM).
func (s *Server) handleTencentCostVoucherByOwner(w http.ResponseWriter, r *http.Request) {
	client, err := s.tencentClient(r)
	if err != nil {
		writeTencentClientErr(w, err)
		return
	}
	month := strings.TrimSpace(r.URL.Query().Get("month"))
	body, err := client.VoucherByOwnerJSON(r.Context(), month)
	if err != nil {
		writeError(w, http.StatusBadGateway, "tencent_api_error", err.Error())
		return
	}
	writeRawData(w, body)
}

// handleTencentCostVoucherUsage returns the deduction history for one voucher.
func (s *Server) handleTencentCostVoucherUsage(w http.ResponseWriter, r *http.Request) {
	voucherID := strings.TrimSpace(r.PathValue("voucher_id"))
	if voucherID == "" {
		writeError(w, http.StatusBadRequest, "missing_param", "voucher_id is required")
		return
	}
	client, err := s.tencentClient(r)
	if err != nil {
		writeTencentClientErr(w, err)
		return
	}
	body, err := client.VoucherUsageJSON(r.Context(), voucherID)
	if err != nil {
		writeError(w, http.StatusBadGateway, "tencent_api_error", err.Error())
		return
	}
	writeRawData(w, body)
}

